// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/3/2026, 11:56:40 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["L:/Frontend/Vercel/prajaukti-pata/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","L:/Frontend/Vercel/prajaukti-pata/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","L:/Frontend/Vercel/prajaukti-pata/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","L:/Frontend/Vercel/prajaukti-pata/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","L:/Frontend/Vercel/prajaukti-pata/app/plugins/**/*.{js,ts,mjs}","L:/Frontend/Vercel/prajaukti-pata/app/composables/**/*.{js,ts,mjs}","L:/Frontend/Vercel/prajaukti-pata/app/utils/**/*.{js,ts,mjs}","L:/Frontend/Vercel/prajaukti-pata/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","L:/Frontend/Vercel/prajaukti-pata/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","L:/Frontend/Vercel/prajaukti-pata/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","L:/Frontend/Vercel/prajaukti-pata/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;